dark_theme:
  type: bool
  default: false
  description:
    en: 'Select to for use with a Dark Color Palette.'
post_border_color:
  type: string
  default: "#D5D5D5"
  description:
    en: 'Custom border color between posts. Dark theme option above must NOT be selected.'
embedded_post_border_color:
  type: string
  default: "#C5C5C5"
  description:
    en: 'Custom border color around embedded posts. Dark theme option above must NOT be selected.'        
large_avatar:
  type: bool
  default: false
  description:
    en: 'Select for use with large (90px vs 45px) avatars on screens > 630px'
reminder_message: 
  type: bool
  default: false
  description:
    en: 'Select to show dismissible reminder message below header to use in Desktop View. Message sets a cookie when dismissed.'
message_color: 
  type: string
  default: "#FFF"
  description:
    en: 'Text color of the message. Default is White. The Background color is the Danger color from your palette'
